export enum Character {
  Individualistic = '개성적인',
  Responsible = '책임감있는',
  Passionate = '열정적인',
  Cute = '귀여운',
  Optimistic = '낙천적인',
  Humorous = '유머있는',
  Calm = '차분한',
  Intellectual = '지적인',
  Delicate = '섬세한',
  Blunt = '무뚝뚝한',
  Extroverted = '외향적인',
  Introverted = '내향적인',
  Friendly = '상냥한',
  Emotional = '감성적인',
}
