export enum Character {
  Individualistic = '개성적인',
  MZ = 'MZ',
  Passionate = '열정적인',
  Cute = '귀여운',
  Optimistic = '낙천적인',
  Humorous = '유머있는',
  Calm = '차분한',
  Homebody = '집돌이',
  Delicate = '섬세한',
  Confucianism = '유교중시',
  Otaku = '오타쿠',
  Godlife = '갓생러',
  Friendly = '상냥한',
  Emotional = '감성적인',
}
