export enum Mbti {
    INFP = 'infp',
    INFJ = 'infj',
    INTP = 'intp',
    INTJ = 'intj',
    ISFP = 'isfp',
    ISFJ = 'isfj',
    ISTP = 'istp',
    ISTJ = 'istj',
    ENFP = 'enfp',
    ENFJ = 'enfj',
    ENTP = 'entp',
    ENTJ = 'entj',
    ESFP = 'esfp',
    ESFJ = 'esfj',
    ESTP = 'estp',
    ESTJ = 'estj',
}