export enum Page {
  phoneNumber = 1,
  checkPhoneNumber = 2,
  birth = 3,
  sex = 4,
  region = 5,
  religion = 6,
  sexOrient = 7,
  drink = 8,
  cigarette = 9,
  height = 10,
  major = 11,
  mbti = 12,
  character = 13,
  hobby = 14,
  images = 15,
  job = 16,
}
