export enum Page {
  phoneNumber = 1,
  checkPhoneNumber = 2,
  birth = 3,
  sex = 4,
  region = 5,
  religion = 6,
  sexOrient = 7,
  drink = 8,
  cigarette = 9,
  height = 10,
  mbti = 11,
  character = 12,
  hobby = 13,
  images = 14,
  job = 15,
}
